import { RoleConfig } from "./types";

export const DEFAULT_ROLES: RoleConfig[] = [
  // ═══════════════════════════════════════════════════════════════
  // تیم مافیا
  // ═══════════════════════════════════════════════════════════════
  {
    name: "پدرخوانده",
    team: "mafia",
    count: 0,
    description: "رهبر مافیا. تیر شبانه با تأیید او زده میشود. استعلام شهروند میخورد",
    color: "#dc2626",
    icon: "🎩",
  },
  {
    name: "مافیا ساده",
    team: "mafia",
    count: 1,
    description: "عضو تیم مافیا. هر شب در تصمیم تیر شرکت میکند",
    color: "#ef4444",
    icon: "🔫",
  },
  {
    name: "تفنگدار مافیا",
    team: "mafia",
    count: 0,
    description: "یک بار در روز میتواند شلیک کند. با مرگ خودش هم فعال میشود",
    color: "#b91c1c",
    icon: "💣",
  },
  {
    name: "رُل‌زن",
    team: "mafia",
    count: 0,
    description: "شب‌ها میتواند نقش خود را با یک شهروند تعویض کند",
    color: "#f87171",
    icon: "🎭",
  },
  {
    name: "گروگان‌گیر",
    team: "mafia",
    count: 0,
    description: "یک بار میتواند بازیکنی را گروگان بگیرد. اگر مافیا رأی بیاورد، گروگان هم میمیرد",
    color: "#991b1b",
    icon: "🪢",
  },
  {
    name: "جاسوس",
    team: "mafia",
    count: 0,
    description: "استعلام شهروند میخورد. شب‌ها میتواند یک نفر را شنود کند",
    color: "#e11d48",
    icon: "🕵️",
  },
  {
    name: "مذاکره‌کننده",
    team: "mafia",
    count: 0,
    description: "یک بار میتواند رأی‌گیری روز را کنسل کند",
    color: "#f43f5e",
    icon: "🤝",
  },
  {
    name: "آرسونیست",
    team: "mafia",
    count: 0,
    description: "شب‌ها یک نفر را علامت میزند. یک بار میتواند همه علامت‌دارها را بسوزاند",
    color: "#ea580c",
    icon: "🔥",
  },
  {
    name: "ساقی",
    team: "mafia",
    count: 0,
    description: "هر شب یک نفر را مسموم میکند و قدرت شبانه‌اش را خنثی میکند",
    color: "#c2410c",
    icon: "🍷",
  },
  {
    name: "فریب‌کار",
    team: "mafia",
    count: 0,
    description: "استعلام او مستقل میخورد. میتواند نقش دروغی نشان دهد",
    color: "#fb923c",
    icon: "🃏",
  },

  // ═══════════════════════════════════════════════════════════════
  // تیم شهروند
  // ═══════════════════════════════════════════════════════════════
  {
    name: "شهروند ساده",
    team: "citizen",
    count: 2,
    description: "نقش خاصی ندارد. با رأی و منطق تیمش را نجات میدهد",
    color: "#6b7280",
    icon: "👤",
  },
  {
    name: "کارآگاه",
    team: "citizen",
    count: 0,
    description: "هر شب هویت یک نفر را استعلام میگیرد (مافیا یا شهروند)",
    color: "#3b82f6",
    icon: "🔍",
  },
  {
    name: "دکتر",
    team: "citizen",
    count: 0,
    description: "هر شب یک نفر را نجات میدهد. نمیتواند دو شب پشت سر هم یک نفر را سیو کند",
    color: "#22c55e",
    icon: "💊",
  },
  {
    name: "تک‌تیرانداز",
    team: "citizen",
    count: 0,
    description: "یک بار در شب میتواند شلیک کند. اگر به شهروند بزند خودش هم میمیرد",
    color: "#f59e0b",
    icon: "🎯",
  },
  {
    name: "زره‌پوش",
    team: "citizen",
    count: 0,
    description: "یک بار از مرگ جان سالم به در میبرد (ضد تیر)",
    color: "#0ea5e9",
    icon: "🛡️",
  },
  {
    name: "کشیش",
    team: "citizen",
    count: 0,
    description: "یک بار میتواند بازیکن حذف‌شده را به بازی برگرداند",
    color: "#a78bfa",
    icon: "✝️",
  },
  {
    name: "شهردار",
    team: "citizen",
    count: 0,
    description: "رأی او در رأی‌گیری دو برابر حساب میشود",
    color: "#14b8a6",
    icon: "🏛️",
  },
  {
    name: "نگهبان",
    team: "citizen",
    count: 0,
    description: "هر شب از یک نفر محافظت میکند. اگر مافیا به آن فرد تیر بزند، نگهبان میمیرد",
    color: "#059669",
    icon: "💂",
  },
  {
    name: "افشاگر",
    team: "citizen",
    count: 0,
    description: "با مرگش نقش یکی از مافیاها فاش میشود",
    color: "#8b5cf6",
    icon: "📢",
  },
  {
    name: "قاضی",
    team: "citizen",
    count: 0,
    description: "یک بار میتواند اعدام روزانه را لغو کند",
    color: "#6366f1",
    icon: "⚖️",
  },
  {
    name: "کابوی",
    team: "citizen",
    count: 0,
    description: "یک بار در روز میتواند به کسی شلیک کند (حتی به خودش ضرر میزند اگر اشتباه بزند)",
    color: "#d97706",
    icon: "🤠",
  },
  {
    name: "خبرنگار",
    team: "citizen",
    count: 0,
    description: "هر شب میتواند دو نفر را مقایسه کند و بفهمد هم‌تیمی‌اند یا نه",
    color: "#0284c7",
    icon: "📰",
  },
  {
    name: "چشم‌بند",
    team: "citizen",
    count: 0,
    description: "هر شب یک نفر را کور میکند و اقدام شبانه‌اش را خنثی میکند",
    color: "#7c3aed",
    icon: "🙈",
  },
  {
    name: "ردیاب",
    team: "citizen",
    count: 0,
    description: "هر شب میفهمد یک نفر به خانه چه کسی رفته است",
    color: "#2563eb",
    icon: "📡",
  },
  {
    name: "تله‌گذار",
    team: "citizen",
    count: 0,
    description: "هر شب تله میگذارد. اگر کسی به خانه‌اش بیاید، هویتش فاش میشود",
    color: "#16a34a",
    icon: "🪤",
  },
  {
    name: "جلاد",
    team: "citizen",
    count: 0,
    description: "یک بار در بازی میتواند در شب مستقیماً یک نفر را اعدام کند",
    color: "#dc2626",
    icon: "⚔️",
  },
  {
    name: "پزشک‌قانونی",
    team: "citizen",
    count: 0,
    description: "وقتی کسی حذف میشود، نقشش را میفهمد (فقط خودش میداند)",
    color: "#0d9488",
    icon: "🔬",
  },
  {
    name: "محافظ شخصی",
    team: "citizen",
    count: 0,
    description: "یک بار جای بازیکن دیگری میمیرد",
    color: "#4ade80",
    icon: "🦸",
  },
  {
    name: "جادوگر سفید",
    team: "citizen",
    count: 0,
    description: "یک بار میتواند نقش واقعی خودش را به همه نشان دهد و همه باور میکنند",
    color: "#c084fc",
    icon: "🧙",
  },
  {
    name: "مأمور مخفی",
    team: "citizen",
    count: 0,
    description: "استعلام مافیا میخورد ولی در واقع شهروند است",
    color: "#4f46e5",
    icon: "🥷",
  },

  // ═══════════════════════════════════════════════════════════════
  // مستقل / ثالث
  // ═══════════════════════════════════════════════════════════════
  {
    name: "برنده مستقل",
    team: "independent",
    count: 0,
    description: "اگر تا آخر بازی زنده بماند، برنده میشود (همراه با تیم برنده)",
    color: "#a855f7",
    icon: "🦊",
  },
  {
    name: "دلقک",
    team: "independent",
    count: 0,
    description: "اگر در رأی‌گیری روزانه اعدام شود، برنده میشود!",
    color: "#e879f9",
    icon: "🤡",
  },
  {
    name: "سریال‌کیلر",
    team: "independent",
    count: 0,
    description: "هر شب یک نفر را میکشد. برای برد باید تنها بازمانده باشد",
    color: "#be123c",
    icon: "🔪",
  },
  {
    name: "کولی",
    team: "independent",
    count: 0,
    description: "اگر شب اول زنده بماند، هر شب نقش یک نفر را یاد میگیرد",
    color: "#d946ef",
    icon: "🔮",
  },
  {
    name: "عروسک‌گردان",
    team: "independent",
    count: 0,
    description: "هر شب یک نفر را کنترل میکند و اقدامش را به سمت شخص دیگری هدایت میکند",
    color: "#a21caf",
    icon: "🎪",
  },
  {
    name: "عاشق",
    team: "independent",
    count: 0,
    description: "شب اول یک نفر را انتخاب میکند. اگر هر کدام بمیرند، دیگری هم میمیرد",
    color: "#ec4899",
    icon: "💕",
  },
  {
    name: "جن",
    team: "independent",
    count: 0,
    description: "بعد از مرگ همچنان میتواند یک شب دیگر اقدام کند",
    color: "#7e22ce",
    icon: "👻",
  },
  {
    name: "خرابکار",
    team: "independent",
    count: 0,
    description: "هدفش ایجاد هرج و مرج است. یک بار نتیجه رأی‌گیری را معکوس میکند",
    color: "#f97316",
    icon: "💀",
  },
  {
    name: "قمارباز",
    team: "independent",
    count: 0,
    description: "هر شب حدس میزند نقش یک نفر چیست. اگر درست حدس بزند، آن فرد میمیرد",
    color: "#eab308",
    icon: "🎰",
  },
  {
    name: "تقلیدگر",
    team: "independent",
    count: 0,
    description: "شب اول نقش فرد مُرده اول را کپی میکند و با آن نقش بازی میکند",
    color: "#06b6d4",
    icon: "🪞",
  },
];

export const ROLE_TEAMS = {
  mafia: { label: "مافیا", color: "#ef4444" },
  citizen: { label: "شهروند", color: "#22c55e" },
  independent: { label: "مستقل", color: "#a855f7" },
};

// گروه‌بندی نقش‌ها برای شب
export const NIGHT_GROUPS = [
  { id: "mafia", label: "مافیا", icon: "🔫", color: "#ef4444" },
  { id: "دکتر", label: "دکتر", icon: "💊", color: "#22c55e" },
  { id: "کارآگاه", label: "کارآگاه", icon: "🔍", color: "#3b82f6" },
  { id: "تک‌تیرانداز", label: "تک‌تیرانداز", icon: "🎯", color: "#f59e0b" },
  { id: "نگهبان", label: "نگهبان", icon: "💂", color: "#059669" },
  { id: "چشم‌بند", label: "چشم‌بند", icon: "🙈", color: "#7c3aed" },
  { id: "ردیاب", label: "ردیاب", icon: "📡", color: "#2563eb" },
  { id: "خبرنگار", label: "خبرنگار", icon: "📰", color: "#0284c7" },
  { id: "کشیش", label: "کشیش", icon: "✝️", color: "#a78bfa" },
  { id: "سریال‌کیلر", label: "سریال‌کیلر", icon: "🔪", color: "#be123c" },
  { id: "کولی", label: "کولی", icon: "🔮", color: "#d946ef" },
  { id: "عروسک‌گردان", label: "عروسک‌گردان", icon: "🎪", color: "#a21caf" },
  { id: "عاشق", label: "عاشق", icon: "💕", color: "#ec4899" },
  { id: "قمارباز", label: "قمارباز", icon: "🎰", color: "#eab308" },
  { id: "ساقی", label: "ساقی", icon: "🍷", color: "#c2410c" },
  { id: "آرسونیست", label: "آرسونیست", icon: "🔥", color: "#ea580c" },
  { id: "جلاد", label: "جلاد", icon: "⚔️", color: "#dc2626" },
  { id: "تله‌گذار", label: "تله‌گذار", icon: "🪤", color: "#16a34a" },
];

// سناریوهای پیشنهادی (اپدیت ۵)
export const GAME_SCENARIOS = [
  {
    name: "کلاسیک ۵ نفره",
    minPlayers: 5,
    maxPlayers: 5,
    roles: [
      { name: "مافیا ساده", count: 1 },
      { name: "دکتر", count: 1 },
      { name: "کارآگاه", count: 1 },
      { name: "شهروند ساده", count: 2 },
    ],
    voteThreshold: "اکثریت ساده (۵۰٪ + ۱)",
  },
  {
    name: "کلاسیک ۸ نفره",
    minPlayers: 8,
    maxPlayers: 8,
    roles: [
      { name: "پدرخوانده", count: 1 },
      { name: "مافیا ساده", count: 1 },
      { name: "دکتر", count: 1 },
      { name: "کارآگاه", count: 1 },
      { name: "تک‌تیرانداز", count: 1 },
      { name: "شهروند ساده", count: 3 },
    ],
    voteThreshold: "اکثریت ساده",
  },
  {
    name: "حرفه‌ای ۱۰ نفره",
    minPlayers: 10,
    maxPlayers: 10,
    roles: [
      { name: "پدرخوانده", count: 1 },
      { name: "مافیا ساده", count: 2 },
      { name: "دکتر", count: 1 },
      { name: "کارآگاه", count: 1 },
      { name: "تک‌تیرانداز", count: 1 },
      { name: "نگهبان", count: 1 },
      { name: "شهروند ساده", count: 3 },
    ],
    voteThreshold: "اکثریت ساده",
  },
  {
    name: "جنگ بزرگ ۱۲ نفره",
    minPlayers: 12,
    maxPlayers: 12,
    roles: [
      { name: "پدرخوانده", count: 1 },
      { name: "مافیا ساده", count: 2 },
      { name: "تفنگدار مافیا", count: 1 },
      { name: "دکتر", count: 1 },
      { name: "کارآگاه", count: 1 },
      { name: "تک‌تیرانداز", count: 1 },
      { name: "نگهبان", count: 1 },
      { name: "زره‌پوش", count: 1 },
      { name: "سریال‌کیلر", count: 1 },
      { name: "شهروند ساده", count: 2 },
    ],
    voteThreshold: "اکثریت ساده",
  },
  {
    name: "هرج و مرج ۱۵ نفره",
    minPlayers: 15,
    maxPlayers: 16,
    roles: [
      { name: "پدرخوانده", count: 1 },
      { name: "مافیا ساده", count: 2 },
      { name: "تفنگدار مافیا", count: 1 },
      { name: "ساقی", count: 1 },
      { name: "دکتر", count: 1 },
      { name: "کارآگاه", count: 1 },
      { name: "تک‌تیرانداز", count: 1 },
      { name: "نگهبان", count: 1 },
      { name: "خبرنگار", count: 1 },
      { name: "شهردار", count: 1 },
      { name: "سریال‌کیلر", count: 1 },
      { name: "دلقک", count: 1 },
      { name: "شهروند ساده", count: 2 },
    ],
    voteThreshold: "اکثریت ساده",
  },
];

// آستانه رأی بر اساس تعداد بازیکنان زنده
export function getVoteThreshold(alivePlayers: number): number {
  return Math.floor(alivePlayers / 2) + 1;
}

// اکشن‌های شبانه هر نقش
export const ROLE_NIGHT_ACTIONS: Record<string, { action: string; label: string; sound: string }> = {
  "مافیا ساده":    { action: "shoot",       label: "تیر زدن",   sound: "gun" },
  "پدرخوانده":     { action: "shoot",       label: "تیر زدن",   sound: "gun" },
  "تفنگدار مافیا": { action: "shoot",       label: "تیر زدن",   sound: "gun" },
  "دکتر":          { action: "heal",        label: "شفا دادن",  sound: "heal" },
  "کارآگاه":       { action: "investigate",  label: "استعلام",    sound: "investigate" },
  "تک‌تیرانداز":    { action: "snipe",       label: "اسنایپ",     sound: "snipe" },
  "نگهبان":        { action: "guard",       label: "محافظت",     sound: "guard" },
  "چشم‌بند":       { action: "block",       label: "کور کردن",   sound: "block" },
  "ردیاب":         { action: "track",       label: "ردیابی",     sound: "track" },
  "خبرنگار":       { action: "compare",     label: "مقایسه",     sound: "investigate" },
  "کشیش":          { action: "revive",      label: "احیا",       sound: "revive" },
  "سریال‌کیلر":    { action: "kill",        label: "کشتن",       sound: "gun" },
  "کولی":          { action: "fortune",     label: "پیشگویی",    sound: "special" },
  "عروسک‌گردان":   { action: "control",     label: "کنترل",      sound: "special" },
  "عاشق":          { action: "choose_love", label: "انتخاب عشق", sound: "love" },
  "قمارباز":       { action: "gamble",      label: "حدس نقش",    sound: "special" },
  "ساقی":          { action: "poison",      label: "مسموم کردن", sound: "poison" },
  "آرسونیست":      { action: "mark",        label: "علامت‌گذاری", sound: "fire" },
  "جلاد":          { action: "execute",     label: "اعدام",      sound: "gun" },
  "تله‌گذار":      { action: "trap",        label: "تله‌گذاری",  sound: "trap" },
  "رُل‌زن":        { action: "swap",        label: "تعویض نقش",  sound: "special" },
  "گروگان‌گیر":    { action: "hostage",     label: "گروگان‌گیری", sound: "special" },
  "جاسوس":         { action: "spy",         label: "شنود",       sound: "investigate" },
  "تقلیدگر":       { action: "copy",        label: "تقلید",      sound: "special" },
  "فریب‌کار":      { action: "deceive",     label: "فریب",       sound: "special" },
};

// لیست صداهای مورد نیاز
export const SOUND_FILES = [
  { name: "day",         description: "موزیک پس‌زمینه روز (loop)" },
  { name: "night",       description: "موزیک پس‌زمینه شب (loop)" },
  { name: "rooster",     description: "صدای خروس — هنگام روز شدن" },
  { name: "wolf",        description: "صدای گرگ — هنگام شب شدن" },
  { name: "gun",         description: "صدای تیر — تیر مافیا/اسنایپر/تفنگدار" },
  { name: "heal",        description: "صدای درمان — شفای دکتر" },
  { name: "investigate", description: "صدای استعلام — کارآگاه/خبرنگار/جاسوس" },
  { name: "snipe",       description: "صدای اسنایپ — تک‌تیرانداز" },
  { name: "guard",       description: "صدای محافظت — نگهبان" },
  { name: "block",       description: "صدای مسدود — چشم‌بند" },
  { name: "track",       description: "صدای ردیابی — ردیاب" },
  { name: "revive",      description: "صدای احیا — کشیش" },
  { name: "special",     description: "صدای خاص — عمومی" },
  { name: "love",        description: "صدای عاشق — انتخاب عشق" },
  { name: "poison",      description: "صدای مسموم — ساقی" },
  { name: "fire",        description: "صدای آتش — آرسونیست" },
  { name: "trap",        description: "صدای تله — تله‌گذار" },
  { name: "vote",        description: "صدای رأی‌گیری — شروع نظرسنجی" },
  { name: "eliminate",   description: "صدای اخراج — حذف بازیکن از رأی‌گیری" },
  { name: "win",         description: "صدای پیروزی — پایان بازی" },
];
